package com.example.mysqloracle.param;

/**
 * 1是，0否
 */
public enum NationalityEnum {

    ALB("ALB","阿尔巴尼亚"),
    DZA("DZA","阿尔及利亚"),
    AFG("AFG","阿富汗"),
    ARG("ARG","阿根廷"),
    ARE("ARE","阿联酋"),
    ABW("ABW","阿鲁巴"),
    OMN("OMN","阿曼"),
    AZE("AZE","阿塞拜疆"),
    EGY("EGY","埃及"),
    ETH("ETH","埃塞俄比亚"),
    IRL("IRL","爱尔兰"),
    EST("EST","爱沙尼亚"),
    AND("AND","安道尔"),
    AGO("AGO","安哥拉"),
    AIA("AIA","安圭拉"),
    ATG("ATG","安提瓜和巴布达"),
    AUT("AUT","奥地利"),
    AUS("AUS","澳大利亚"),
    BRB("BRB","巴巴多斯"),
    PNG("PNG","巴布亚新几内亚"),
    BHS("BHS","巴哈马"),
    PAK("PAK","巴基斯坦"),
    PRY("PRY","巴拉圭"),
    PST("PST","巴勒斯坦"),
    BHR("BHR","巴林"),
    PAN("PAN","巴拿马"),
    BRA("BRA","巴西"),
    BLR("BLR","白俄罗斯"),
    BMU("BMU","百慕大"),
    BGR("BGR","保加利亚"),
    MNP("MNP","北马里亚纳"),
    BEN("BEN","贝宁"),
    BEL("BEL","比利时"),
    ISL("ISL","冰岛"),
    BOL("BOL","玻利维亚"),
    PRI("PRI","波多黎各"),
    BIH("BIH","波黑"),
    POL("POL","波兰"),
    BWA("BWA","博茨瓦纳"),
    BLZ("BLZ","伯利兹"),
    BTN("BTN","不丹"),
    BFA("BFA","布基纳法索"),
    BDI("BDI","布隆迪"),
    BVT("BVT","布维岛"),
    PRK("PRK","朝鲜"),
    GNQ("GNQ","赤道几内亚"),
    DNK("DNK","丹麦"),
    DEU("DEU","德国"),
    TMP("TMP","东帝汶"),
    TGO("TGO","多哥"),
    DOM("DOM","多米尼加共和国"),
    DMA("DMA","多米尼克"),
    RUS("RUS","俄罗斯联邦"),
    ECU("ECU","厄瓜多尔"),
    ERI("ERI","厄立特里亚"),
    FRA("FRA","法国"),
    FRO("FRO","法罗群岛"),
    PYF("PYF","法属波利尼西亚"),
    GUF("GUF","法属圭亚那"),
    ATF("ATF","法属南部领土"),
    PHL("PHL","菲律宾"),
    FIN("FIN","芬兰"),
    CPV("CPV","佛得角"),
    FLK("FLK","福克兰群岛(马尔维纳斯)"),
    GMB("GMB","冈比亚Gambia"),
    COG("COG","刚果（布）"),
    COD("COD","刚果（金）"),
    COL("COL","哥伦比亚"),
    CR("CR","哥斯达黎加"),
    GRD("GRD","格林纳达"),
    GRL("GRL","格陵兰"),
    GEO("GEO","格鲁吉亚"),
    CUB("CUB","古巴"),
    GLP("GLP","瓜德罗普"),
    GUM("GUM","关岛"),
    GUY("GUY","圭亚那"),
    KAZ("KAZ","哈萨克斯坦"),
    HTI("HTI","海地"),
    KOR("KOR","韩国"),
    NLD("NLD","荷兰"),
    ANT("ANT","荷属安的列斯"),
    HMD("HMD","赫德岛和麦克唐纳岛"),
    HND("HND","洪都拉斯"),
    KIR("KIR","基里巴斯"),
    DJI("DJI","吉布提"),
    KGZ("KGZ","吉尔吉斯斯坦"),
    GIN("GIN","几内亚"),
    GNB("GNB","几内亚比绍"),
    CAN("CAN","加拿大"),
    GHA("GHA","加纳"),
    GAB("GAB","加蓬"),
    KHM("KHM","柬埔寨"),
    CZE("CZE","捷克"),
    ZWE("ZWE","津巴布韦"),
    CMR("CMR","喀麦隆"),
    QAT("QAT","卡塔尔"),
    CYM("CYM","开曼群岛"),
    CCK("CCK","科科斯(基林)群岛"),
    COM("COM","科摩罗"),
    CIV("CIV","科特迪瓦"),
    KWT("KWT","科威特"),
    HRV("HRV","克罗地亚"),
    KEN("KEN","肯尼亚"),
    COK("COK","库克群岛"),
    LVA("LVA","拉脱维亚"),
    LSO("LSO","莱索托"),
    LAO("LAO","老挝"),
    LBN("LBN","黎巴嫩"),
    LBR("LBR","利比里亚"),
    LBY("LBY","利比亚"),
    LTU("LTU","立陶宛"),
    LIE("LIE","列支敦士登"),
    REU("REU","留尼汪"),
    LUX("LUX","卢森堡"),
    RWA("RWA","卢旺达"),
    ROM("ROM","罗马尼亚"),
    MDG("MDG","马达加斯加"),
    MLT("MLT","马耳他"),
    MDV("MDV","马尔代夫"),
    MWI("MWI","马拉维"),
    MYS("MYS","马来西亚"),
    MLI("MLI","马里"),
    MHL("MHL","马绍尔群岛"),
    MTQ("MTQ","马提尼克"),
    MYT("MYT","马约特"),
    MUS("MUS","毛里求斯"),
    MRT("MRT","毛里塔尼亚"),
    USA("USA","美国"),
    UMI("UMI","美国本土外小岛屿"),
    ASM("ASM","美属萨摩亚"),
    VIR("VIR","美属维尔京群岛"),
    MNG("MNG","蒙古"),
    MSR("MSR","蒙特塞拉特"),
    BGD("BGD","孟加拉国"),
    PER("PER","秘鲁"),
    FSM("FSM","密克罗尼西亚联邦"),
    MMR("MMR","缅甸"),
    MDA("MDA","摩尔多瓦"),
    MAR("MAR","摩洛哥"),
    MCO("MCO","摩纳哥"),
    MOZ("MOZ","莫桑比克"),
    MEX("MEX","墨西哥"),
    NAM("NAM","纳米比亚"),
    ZAF("ZAF","南非"),
    ATA("ATA","南极洲"),
    SGS("SGS","南乔治亚岛和南桑德韦奇岛"),
    YUG("YUG","南斯拉夫"),
    NPL("NPL","尼泊尔"),
    NIC("NIC","尼加拉瓜"),
    NER("NER","尼日尔"),
    NGA("NGA","尼日利亚"),
    NIU("NIU","纽埃"),
    NOR("NOR","挪威"),
    NFK("NFK","诺福克岛"),
    PLW("PLW","帕劳"),
    PCN("PCN","皮特凯恩群岛"),
    PRT("PRT","葡萄牙"),
    MKD("MKD","前南马其顿"),
    JPN("JPN","日本"),
    SWE("SWE","瑞典"),
    CHE("CHE","瑞士"),
    SLV("SLV","萨尔瓦多"),
    WSM("WSM","萨摩亚"),
    SLE("SLE","塞拉利昂"),
    SEN("SEN","塞内加尔"),
    CYP("CYP","塞浦路斯"),
    SYC("SYC","塞舌尔"),
    SAU("SAU","沙特阿拉伯"),
    CSR("CSR","圣诞岛"),
    STP("STP","圣多美和普林西比"),
    SHN("SHN","圣赫勒拿"),
    KNA("KNA","圣基茨和尼维斯"),
    LCA("LCA","圣卢西亚"),
    SMR("SMR","圣马力诺"),
    SPM("SPM","圣皮埃尔和密克隆"),
    VCT("VCT","圣文森特和格林纳丁斯"),
    LKA("LKA","斯里兰卡"),
    SVK("SVK","斯洛伐克"),
    SVN("SVN","斯洛文尼亚"),
    SJM("SJM","斯瓦尔巴群岛"),
    SWZ("SWZ","斯威士兰"),
    SDN("SDN","苏丹"),
    SUR("SUR","苏里南"),
    SOM("SOM","索马里"),
    SLB("SLB","所罗门群岛"),
    TJK("TJK","塔吉克斯坦"),
    THA("THA","泰国"),
    TZA("TZA","坦桑尼亚"),
    TON("TON","汤加"),
    TCA("TCA","特克斯科斯群岛"),
    TTO("TTO","特立尼达和多巴哥"),
    TUN("TUN","突尼斯"),
    TUV("TUV","图瓦卢"),
    TUR("TUR","土耳其"),
    TKM("TKM","土库曼斯坦"),
    TKL("TKL","托克劳"),
    WLF("WLF","瓦利斯和富图纳"),
    VUT("VUT","瓦努阿图"),
    GTM("GTM","危地马拉"),
    VEN("VEN","委内瑞拉"),
    BRN("BRN","文莱"),
    UGA("UGA","乌干达"),
    UKR("UKR","乌克兰"),
    URY("URY","乌拉圭"),
    UZB("UZB","乌兹别克斯坦"),
    ESP("ESP","西班牙"),
    ESH("ESH","西撒哈拉"),
    GRC("GRC","希腊"),
    HK("HK","香港"),
    SGP("SGP","新加坡"),
    NCL("NCL","新喀里多尼亚"),
    NZL("NZL","新西兰"),
    HUN("HUN","匈牙利"),
    SYR("SYR","叙利亚"),
    JAM("JAM","牙买加"),
    ARM("ARM","亚美尼亚"),
    YEM("YEM","也门"),
    IRQ("IRQ","伊拉克"),
    IRN("IRN","伊朗"),
    ISR("ISR","以色列"),
    ITA("ITA","意大利"),
    IND("IND","印度"),
    IDN("IDN","印度尼西亚"),
    GBR("GBR","英国"),
    VGB("VGB","英属维尔京群岛"),
    IOT("IOT","英属印度洋领土"),
    JOR("JOR","约旦"),
    VNM("VNM","越南"),
    ZMB("ZMB","赞比亚"),
    TCD("TCD","乍得"),
    GIB("GIB","直布罗陀"),
    CHL("CHL","智利"),
    CAF("CAF","中非"),
    CHN("CHN","中国"),
    MAC("MAC","中国澳门"),
    TWN("TWN","中国台湾"),
    HKG("HKG","中国香港"),
    NRU("NRU","瑙鲁"),
    VAT("VAT","梵蒂冈"),
    FJI("FJI","斐济");
//    86("86","中国"),
//            87("87","中国其他证件");

    private String code;
    private String desc;


    NationalityEnum(String code, String desc) {
        this.code = code;
        this.desc = desc;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }


    public static String getDescByCode(String code){
        for (NationalityEnum ele : values()) {
            if(ele.getCode().equals(code))
                return ele.getDesc();
        }
        return "";//默认为待承保
    }
}
